// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesAgenda.Models;

namespace PageBook.Migrations
{
    [DbContext(typeof(AgendaContext))]
    partial class AgendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("RazorPagesAgenda.Models.AGENDA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Celular");

                    b.Property<string>("DDD");

                    b.Property<string>("Email");

                    b.Property<string>("Empresa");

                    b.Property<string>("Nome");

                    b.HasKey("ID");

                    b.ToTable("AGENDA");
                });
#pragma warning restore 612, 618
        }
    }
}
